config/routes.rb
Rails.application.routes.draw do
  get 'tamuber/index'

  root 'tamuber#index'
  
  resources :trips
  
  get '/pickup', to: 'trips#pickup'
  get '/transit', to: 'trips#transit'
  get '/arrived', to: 'trips#arrived'
  post '/trips/new', to: 'trips#new'
	get '/end', to: 'trips#end'
  get '/cart_not_found', to: 'trips#cart_not_found'
  get '/specify', to: 'trips#specify'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Added the following for signup and logging
  # Edit Manish start
  get    '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #match 'users/show',   to: "trips#specify",      via: :get
  # Edit end
  resources :users
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <<%= link_to_if(logged_in?, "TamUber Students Interface", specify_path,
  id: "logo") {link_to("TamUber Students Interface", root_path, id: "logo")} %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>

            <li><%= link_to "Home", specify_path %></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
    
        <% else %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% unless action_name == "index" %>
      <%= render 'layouts/header' %>
    <% end %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Edit Manish start -->
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBcAKtfKCZNpK5-NZqZk4B1MyAdTgn8Jq4"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    -->
  </head>
  <%= yield %>
</html>